export const TRACK_WIDTH = 50;
export const FIXED_INDICATOR_WIDTH = 12;
export const MAX_TRANSLATION = TRACK_WIDTH - FIXED_INDICATOR_WIDTH;
export const DISCOUNT_PERCENTAGE = 30;
export const PRODUCT_CODE = 32361470;
export const PRODUCT_PRICE = "294";
export const EXTRA_DISCOUNT = "90";
export const OTP_RESEND_TIMER = 30;
export const  CART = "guest_cart";
export const PIN_CODE_LENGTH = 6;
export const OTP_LENGTH = 6;
export const APP_VERSION = "4.2503.21";
export const ESTIMATED_DELIVERY ="15 days"
export const EXCHANGE_DAY = "7 days"
export const LOCALE_DATE_FORMAT = "en-IN";