export const fontFamilies = {
  ralewayExtraBold: "RalewayeExtraBold",
  ralewayBold: "RalewayeBold",
  ralewayMedium: "RalewayeMedium",
  ralewayRegular: "RalewayeRegular",
  nunitoSans: "NunitoSans",
  helveticaBold:'HelveticaBold',
  helvetica:'Helvetica',
  abriFatfaceRegular:'AbriFatfaceRegular',
  ralewayeBold:'RalewayeBold',
  raleway:'Raleway',
  ralewayeMedium:'RalewayeMedium',
  ralewayeSemiBold:'RalewayeSemiBold',
  arial: "Arial",
};